name: Update Videos
on:
  schedule:
    - cron: '5 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: cron job
        run: |
          curl --request POST \
          --url 'https://holoniwa.vercel.app/api/cron' \
          --header 'Authorization: ${{ secrets.MY_API_KEY }}'
